### ISSUE TITLE
How to get the actual datasets?

### ISSUE THREAD

**Issue by costasmexis** [CRANK-MS/CRANK-MS#2]
Very interesting work!
I am not very familiar with these Metabolomics databases, so I could need some help on getting the actual datasets. I understand that these repositories hold the RAW data from some studies. But, how I could get the actual data for ML model training? Are these datasets also available in these databases?
Thank you very much!

**Comment by diana1806** [comment]
Hi @costasmexis,
Thank you for your interest in our research!
Depending on the repository/database and your desired input data format, some studies may already have pre-processed metabolomics data (as in our case). However, if you have RAW data and have access to suitable instrument software (e.g. XCalibur) which can read, process, and extract the data to your desired format, then that would be the easiest go-to option. Otherwise, depending on your research question, there are other APIs tasked to processing RAW data such as Pyteomics. Hope that helps!

**Comment by costasmexis** [comment]
Thank you very very much!
